name: "Create snapshot of pool and farms apy"

on:
  schedule:
    - cron: "0 * * * *"

env:
  solana_version: 1.9.14

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: setup solana
        run: |
          sh -c "$(curl -sSfL https://release.solana.com/v${{ env.solana_version }}/install)"
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          solana-keygen new
      - name: do a snapshot
        run: |
          git config --global user.email stats@invariant.app
          git config --global user.name invariantStats
          export PATH="/home/runner/.local/share/solana/install/active_release/bin:$PATH"
          export ANCHOR_WALLET="/home/runner/.config/solana/id.json"
          npm install
          npm run apyData
          git add ./data
          git commit -m "Snapshot of apy done!"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
      - name: Deploy to Production
        uses: amondnet/vercel-action@v20
        id: deploy-vercel-production
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
          vercel-args: "--prod"
          scope: ${{ secrets.VERCEL_ORG_ID }}
