name: "Manual alph snap"

on: workflow_dispatch

jobs:
  alph-snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: alph snapshot
        working-directory: ./alph
        run: |
          npm install
          npm run snap
      - uses: actions/upload-artifact@v4
        with:
          name: alph-snapshot-${{ github.run_id }}
          path: |
            ./data/alph/
      - name: Commit changes
        run: |
          git config --global user.email stats@invariant.app
          git config --global user.name invariantStats
          git add ./data/
          git commit -m "ALPH manual snapshot of data"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main