name: "Manual vara snap"

on: workflow_dispatch

jobs:
  vara-snap:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "20"
      - name: vara snapshot
        working-directory: ./vara
        run: |
          npm install
          npm run snap
      - uses: actions/upload-artifact@v4
        with:
          name: vara-snapshot-${{ github.run_id }}
          path: |
            ./data/vara/
      - name: Commit changes
        run: |
          git config --global user.email stats@invariant.app
          git config --global user.name invariantStats
          git add ./data/
          git commit -m "Vara Network snapshot of data done!"
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: main
